// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: schema_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Services {

  /// <summary>Holder for reflection information generated from schema_service.proto</summary>
  public static partial class SchemaServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for schema_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SchemaServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRzY2hlbWFfc2VydmljZS5wcm90bxoMc2NoZW1hLnByb3RvMowDCg5NZXNz",
            "YWdlU2VydmljZRJgCipNZXNzYWdlT3ZlcmxheVJlY2VpdmVkS2V5Ym9hcmRJ",
            "bnB1dE1lc3NhZ2USJC5PdmVybGF5UmVjZWl2ZWRLZXlib2FyZElucHV0TWVz",
            "c2FnZRoKLkJvb2xWYWx1ZSIAElgKJk1lc3NhZ2VPdmVybGF5UmVjZWl2ZWRN",
            "b3VzZU1vdmVNZXNzYWdlEiAuT3ZlcmxheVJlY2VpdmVkTW91c2VNb3ZlTWVz",
            "c2FnZRoKLkJvb2xWYWx1ZSIAEloKJ01lc3NhZ2VPdmVybGF5UmVjZWl2ZWRN",
            "b3VzZUlucHV0TWVzc2FnZRIhLk92ZXJsYXlSZWNlaXZlZE1vdXNlSW5wdXRN",
            "ZXNzYWdlGgouQm9vbFZhbHVlIgASYgorTWVzc2FnZU92ZXJsYXlSZWNlaXZl",
            "ZE1vdXNlV2hlZWxNb3ZlTWVzc2FnZRIlLk92ZXJsYXlSZWNlaXZlZE1vdXNl",
            "V2hlZWxNb3ZlTWVzc2FnZRoKLkJvb2xWYWx1ZSIAQhGqAg5Qcm90by5TZXJ2",
            "aWNlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.Messages.SchemaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
