// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: schema_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Proto.Services {
  /// <summary>
  ///*
  /// 
  /// </summary>
  public static partial class MessageService
  {
    static readonly string __ServiceName = "MessageService";

    static readonly grpc::Marshaller<global::Proto.Messages.OverlayReceivedKeyboardInputMessage> __Marshaller_OverlayReceivedKeyboardInputMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Messages.OverlayReceivedKeyboardInputMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.Messages.BoolValue> __Marshaller_BoolValue = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Messages.BoolValue.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.Messages.OverlayReceivedMouseMoveMessage> __Marshaller_OverlayReceivedMouseMoveMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Messages.OverlayReceivedMouseMoveMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.Messages.OverlayReceivedMouseInputMessage> __Marshaller_OverlayReceivedMouseInputMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Messages.OverlayReceivedMouseInputMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage> __Marshaller_OverlayReceivedMouseWheelMoveMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::Proto.Messages.OverlayReceivedKeyboardInputMessage, global::Proto.Messages.BoolValue> __Method_MessageOverlayReceivedKeyboardInputMessage = new grpc::Method<global::Proto.Messages.OverlayReceivedKeyboardInputMessage, global::Proto.Messages.BoolValue>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MessageOverlayReceivedKeyboardInputMessage",
        __Marshaller_OverlayReceivedKeyboardInputMessage,
        __Marshaller_BoolValue);

    static readonly grpc::Method<global::Proto.Messages.OverlayReceivedMouseMoveMessage, global::Proto.Messages.BoolValue> __Method_MessageOverlayReceivedMouseMoveMessage = new grpc::Method<global::Proto.Messages.OverlayReceivedMouseMoveMessage, global::Proto.Messages.BoolValue>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MessageOverlayReceivedMouseMoveMessage",
        __Marshaller_OverlayReceivedMouseMoveMessage,
        __Marshaller_BoolValue);

    static readonly grpc::Method<global::Proto.Messages.OverlayReceivedMouseInputMessage, global::Proto.Messages.BoolValue> __Method_MessageOverlayReceivedMouseInputMessage = new grpc::Method<global::Proto.Messages.OverlayReceivedMouseInputMessage, global::Proto.Messages.BoolValue>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MessageOverlayReceivedMouseInputMessage",
        __Marshaller_OverlayReceivedMouseInputMessage,
        __Marshaller_BoolValue);

    static readonly grpc::Method<global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage, global::Proto.Messages.BoolValue> __Method_MessageOverlayReceivedMouseWheelMoveMessage = new grpc::Method<global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage, global::Proto.Messages.BoolValue>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MessageOverlayReceivedMouseWheelMoveMessage",
        __Marshaller_OverlayReceivedMouseWheelMoveMessage,
        __Marshaller_BoolValue);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Proto.Services.SchemaServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MessageService</summary>
    [grpc::BindServiceMethod(typeof(MessageService), "BindService")]
    public abstract partial class MessageServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Proto.Messages.BoolValue> MessageOverlayReceivedKeyboardInputMessage(global::Proto.Messages.OverlayReceivedKeyboardInputMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseMoveMessage(global::Proto.Messages.OverlayReceivedMouseMoveMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseInputMessage(global::Proto.Messages.OverlayReceivedMouseInputMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseWheelMoveMessage(global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MessageService</summary>
    public partial class MessageServiceClient : grpc::ClientBase<MessageServiceClient>
    {
      /// <summary>Creates a new client for MessageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MessageServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MessageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MessageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MessageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MessageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Proto.Messages.BoolValue MessageOverlayReceivedKeyboardInputMessage(global::Proto.Messages.OverlayReceivedKeyboardInputMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageOverlayReceivedKeyboardInputMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Messages.BoolValue MessageOverlayReceivedKeyboardInputMessage(global::Proto.Messages.OverlayReceivedKeyboardInputMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MessageOverlayReceivedKeyboardInputMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Messages.BoolValue> MessageOverlayReceivedKeyboardInputMessageAsync(global::Proto.Messages.OverlayReceivedKeyboardInputMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageOverlayReceivedKeyboardInputMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Messages.BoolValue> MessageOverlayReceivedKeyboardInputMessageAsync(global::Proto.Messages.OverlayReceivedKeyboardInputMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MessageOverlayReceivedKeyboardInputMessage, null, options, request);
      }
      public virtual global::Proto.Messages.BoolValue MessageOverlayReceivedMouseMoveMessage(global::Proto.Messages.OverlayReceivedMouseMoveMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageOverlayReceivedMouseMoveMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Messages.BoolValue MessageOverlayReceivedMouseMoveMessage(global::Proto.Messages.OverlayReceivedMouseMoveMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MessageOverlayReceivedMouseMoveMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseMoveMessageAsync(global::Proto.Messages.OverlayReceivedMouseMoveMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageOverlayReceivedMouseMoveMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseMoveMessageAsync(global::Proto.Messages.OverlayReceivedMouseMoveMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MessageOverlayReceivedMouseMoveMessage, null, options, request);
      }
      public virtual global::Proto.Messages.BoolValue MessageOverlayReceivedMouseInputMessage(global::Proto.Messages.OverlayReceivedMouseInputMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageOverlayReceivedMouseInputMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Messages.BoolValue MessageOverlayReceivedMouseInputMessage(global::Proto.Messages.OverlayReceivedMouseInputMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MessageOverlayReceivedMouseInputMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseInputMessageAsync(global::Proto.Messages.OverlayReceivedMouseInputMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageOverlayReceivedMouseInputMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseInputMessageAsync(global::Proto.Messages.OverlayReceivedMouseInputMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MessageOverlayReceivedMouseInputMessage, null, options, request);
      }
      public virtual global::Proto.Messages.BoolValue MessageOverlayReceivedMouseWheelMoveMessage(global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageOverlayReceivedMouseWheelMoveMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Messages.BoolValue MessageOverlayReceivedMouseWheelMoveMessage(global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MessageOverlayReceivedMouseWheelMoveMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseWheelMoveMessageAsync(global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageOverlayReceivedMouseWheelMoveMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Messages.BoolValue> MessageOverlayReceivedMouseWheelMoveMessageAsync(global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MessageOverlayReceivedMouseWheelMoveMessage, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MessageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MessageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MessageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_MessageOverlayReceivedKeyboardInputMessage, serviceImpl.MessageOverlayReceivedKeyboardInputMessage)
          .AddMethod(__Method_MessageOverlayReceivedMouseMoveMessage, serviceImpl.MessageOverlayReceivedMouseMoveMessage)
          .AddMethod(__Method_MessageOverlayReceivedMouseInputMessage, serviceImpl.MessageOverlayReceivedMouseInputMessage)
          .AddMethod(__Method_MessageOverlayReceivedMouseWheelMoveMessage, serviceImpl.MessageOverlayReceivedMouseWheelMoveMessage).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MessageServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_MessageOverlayReceivedKeyboardInputMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Messages.OverlayReceivedKeyboardInputMessage, global::Proto.Messages.BoolValue>(serviceImpl.MessageOverlayReceivedKeyboardInputMessage));
      serviceBinder.AddMethod(__Method_MessageOverlayReceivedMouseMoveMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Messages.OverlayReceivedMouseMoveMessage, global::Proto.Messages.BoolValue>(serviceImpl.MessageOverlayReceivedMouseMoveMessage));
      serviceBinder.AddMethod(__Method_MessageOverlayReceivedMouseInputMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Messages.OverlayReceivedMouseInputMessage, global::Proto.Messages.BoolValue>(serviceImpl.MessageOverlayReceivedMouseInputMessage));
      serviceBinder.AddMethod(__Method_MessageOverlayReceivedMouseWheelMoveMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Messages.OverlayReceivedMouseWheelMoveMessage, global::Proto.Messages.BoolValue>(serviceImpl.MessageOverlayReceivedMouseWheelMoveMessage));
    }

  }
}
#endregion
