# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\x9f\x01\n#OverlayReceivedKeyboardInputMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x43\n\nevent_type\x18\x02 \x01(\x0e\x32/.OverlayReceivedKeyboardInputMessage.EVENT_TYPE\"&\n\nEVENT_TYPE\x12\x0c\n\x08KEY_DOWN\x10\x00\x12\n\n\x06KEY_UP\x10\x01\"I\n\x1fOverlayReceivedMouseMoveMessage\x12\x12\n\nx_position\x18\x01 \x01(\r\x12\x12\n\ny_position\x18\x02 \x01(\r\"\x86\x02\n OverlayReceivedMouseInputMessage\x12@\n\nevent_type\x18\x01 \x01(\x0e\x32,.OverlayReceivedMouseInputMessage.EVENT_TYPE\x12\x42\n\x0b\x62utton_type\x18\x02 \x01(\x0e\x32-.OverlayReceivedMouseInputMessage.BUTTON_TYPE\",\n\nEVENT_TYPE\x12\x0f\n\x0b\x42UTTON_DOWN\x10\x00\x12\r\n\tBUTTON_UP\x10\x01\".\n\x0b\x42UTTON_TYPE\x12\t\n\x05RIGHT\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\n\n\x06MIDDLE\x10\x02\"5\n$OverlayReceivedMouseWheelMoveMessage\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\r\"\x1a\n\tBoolValue\x12\r\n\x05value\x18\x01 \x01(\x08\x42\x11\xaa\x02\x0eProto.Messagesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\016Proto.Messages'
  _OVERLAYRECEIVEDKEYBOARDINPUTMESSAGE._serialized_start=17
  _OVERLAYRECEIVEDKEYBOARDINPUTMESSAGE._serialized_end=176
  _OVERLAYRECEIVEDKEYBOARDINPUTMESSAGE_EVENT_TYPE._serialized_start=138
  _OVERLAYRECEIVEDKEYBOARDINPUTMESSAGE_EVENT_TYPE._serialized_end=176
  _OVERLAYRECEIVEDMOUSEMOVEMESSAGE._serialized_start=178
  _OVERLAYRECEIVEDMOUSEMOVEMESSAGE._serialized_end=251
  _OVERLAYRECEIVEDMOUSEINPUTMESSAGE._serialized_start=254
  _OVERLAYRECEIVEDMOUSEINPUTMESSAGE._serialized_end=516
  _OVERLAYRECEIVEDMOUSEINPUTMESSAGE_EVENT_TYPE._serialized_start=424
  _OVERLAYRECEIVEDMOUSEINPUTMESSAGE_EVENT_TYPE._serialized_end=468
  _OVERLAYRECEIVEDMOUSEINPUTMESSAGE_BUTTON_TYPE._serialized_start=470
  _OVERLAYRECEIVEDMOUSEINPUTMESSAGE_BUTTON_TYPE._serialized_end=516
  _OVERLAYRECEIVEDMOUSEWHEELMOVEMESSAGE._serialized_start=518
  _OVERLAYRECEIVEDMOUSEWHEELMOVEMESSAGE._serialized_end=571
  _BOOLVALUE._serialized_start=573
  _BOOLVALUE._serialized_end=599
# @@protoc_insertion_point(module_scope)
