# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import schema_pb2 as schema__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14schema_service.proto\x1a\x0cschema.proto2\x8c\x03\n\x0eMessageService\x12`\n*MessageOverlayReceivedKeyboardInputMessage\x12$.OverlayReceivedKeyboardInputMessage\x1a\n.BoolValue\"\x00\x12X\n&MessageOverlayReceivedMouseMoveMessage\x12 .OverlayReceivedMouseMoveMessage\x1a\n.BoolValue\"\x00\x12Z\n\'MessageOverlayReceivedMouseInputMessage\x12!.OverlayReceivedMouseInputMessage\x1a\n.BoolValue\"\x00\x12\x62\n+MessageOverlayReceivedMouseWheelMoveMessage\x12%.OverlayReceivedMouseWheelMoveMessage\x1a\n.BoolValue\"\x00\x42\x11\xaa\x02\x0eProto.Servicesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\016Proto.Services'
  _MESSAGESERVICE._serialized_start=39
  _MESSAGESERVICE._serialized_end=435
# @@protoc_insertion_point(module_scope)
